name: saxonpy jobs
on: [push, workflow_dispatch]
jobs:
  Matrix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        python-version: [ '3.6' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: build wheel
        run: |
          pip install -r requirements.txt
          python setup.py bdist_wheel
      - name: delvewheel wheel for multiple Windows OS support.
        run: |
          pip install delvewheel
          delvewheel repair $(ls .\dist\)
          echo "listing the fixed wheels....."
          ls wheelhouse
      - name: install pytest, saxonpy, and test
        run: |
          pip install pytest
          pip install $(ls .\wheelhouse\)
          pytest test_saxonc.py
      - name: upload wheel
        # env:
        #   TWINE_USER: ${{ secrets.TWINE_TU }}
        #   TWINE_PASS: ${{ secrets.TWINE_TP }}
        run: |
          pip install twine
          twine upload --skip-existing --verbose --repository testpypi --username "${{ secrets.TWINE_TU }}" --password "${{ secrets.TWINE_TP }}" wheelhouse\*