name: saxonpy jobs
on: [push, workflow_dispatch]
jobs:
  Matrix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: build wheel
        run: |
          pip install -r requirements.txt
          python setup.py bdist_wheel
      - name: delvewheel wheel for multiple Windows OS support.
        run: |
          pip install delvewheel
          delvewheel repair $(ls .\dist\)
          echo "listing the fixed wheels....."
          ls wheelhouse
      - name: install pytest, saxonpy, and test
        run: |
          pip install pytest
          pip install $(ls .\wheelhouse\)
          pytest test_saxonc.py
      - name: upload wheel
        run: |
          pip install twine
          twine upload --skip-existing --verbose --username "${{ secrets.TWINE_U }}" --password "${{ secrets.TWINE_P }}" wheelhouse\*