name: saxonpy jobs
on: [push, workflow_dispatch]
jobs:
  Matrix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        python-version: [ '3.6' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: build wheel
        run: |
          pip install -r requirements.txt
          python setup.py bdist_wheel
      - name: delvewheel wheel for multiple macOS support.
        run: |
          pip install delvewheel
          delvewheel repair -v $(ls .\dist\)
          echo "listing the fixed wheels....."
          ls wheelhouse
      - name: install pytest, saxonpy, and test
        run: |
          pip install pytest
          pip install $(ls .\wheelhouse\)
          pytest test_saxonc.py
      # - name: upload wheel
      #   env:
      #     TWINE_USER: ${{ secrets.TWINE_USERNAME }}
      #     TWINE_PASS: ${{ secrets.TWINE_PASSWORD }}
      #   run: |
      #     pip install twine
      #     twine upload --skip-existing --verbose -u "$TWINE_USER" -p "$TWINE_PASS" --repository testpypi wheelhouse/*.whl